raw_datasource_name: raw_data
raw_suite_name: raw_data_suite
raw_data_asset_name: train_data
build_data_docs: true
processed_datasource_name: model_input
processed_suite_name: processed_data_suite
processed_data_asset_name: model_train_data

# Target column for prediction
target_column: "Claim Injury Type"

# Data split parameters
test_size: 0.1
val_size: 0.2
random_state: 42

# Data processing parameters
numerical_features:
  - "Age at Injury"
  - "Average Weekly Wage"
  - "Birth Year"
  - "IME-4 Count"
  - "Number of Dependents"
  - "Days_to_C2"
  - "Days_to_C3"
  - "Days_to_First_Hearing"
  - "C-2 Date_Day"
  - "C-2 Date_Month"
  - "C-2 Date_Year"
  - "C-2 Date_DayOfWeek"
  - "C-3 Date_Month"
  - "C-3 Date_Day"
  - "C-3 Date_Year"
  - "C-3 Date_DayOfWeek"
  - "First Hearing Date_Day"
  - "First Hearing Date_Month"
  - "First Hearing Date_Year"
  - "First Hearing Date_DayOfWeek"
  - "Accident Date_Day"
  - "Accident Date_Month"
  - "Accident Date_Year"
  - "Accident Date_DayOfWeek"
  - "Assembly Date_Day"
  - "Assembly Date_Month"
  - "Assembly Date_Year"
  - "Assembly Date_DayOfWeek"

categorical_features:
  - "Alternative Dispute Resolution_U"
  - "Alternative Dispute Resolution_Y"
  - "Enc County of Injury"
  - "Enc District Name"
  - "Enc Industry Code"
  - "Known Accident Date"
  - "Known Assembly Date"
  - "Known C-2 Date"
  - "Known C-3 Date"
  - "Enc WCIO Cause of Injury Code"
  - "Enc WCIO Nature of Injury Code"
  - "Enc WCIO Part Of Body Code"
  - "Enc Zip Code"
  - "Attorney/Representative_Y"
  - "Carrier Type_2A. SIF"
  - "Carrier Type_3A. SELF PUBLIC"
  - "Carrier Type_4A. SELF PRIVATE"
  - "Carrier Type_5D. SPECIAL FUND - UNKNOWN"
  - "Carrier Type_UNKNOWN"
  - "COVID-19 Indicator_Y"
  - "Medical Fee Region_II"
  - "Medical Fee Region_III"
  - "Medical Fee Region_IV"
  - "Medical Fee Region_UK"
  - "Known First Hearing Date"
  - "Known Age at Injury"
  - "Known Birth Year"
  - "Holiday_Accident"
  - "Weekend_Accident"
  - "Risk_Level"
  - "Gender_M"
  - "Gender_Unknown"
  - "Accident_Season_Sin"
  - "Accident_Season_Cos"
  - "Relative_Wage"
  - "Financial Impact Category"
  - "Age_Group"

scaling_method: "standard"
imputation_method: "median"

# Feature engineering parameters
date_columns:
  - "C-2 Date"
  - "C-3 Date"
  - "First Hearing Date"
  - "Accident Date"
  - "Assembly Date"

create_polynomial_features: false
polynomial_degree: 2

# Feature selection parameters
xgb_threshold: "median"
rf_threshold: "median"
max_features: null
selection_method: "union"

# Model parameters
xgb_params:
  n_estimators: 100
  max_depth: 6
  learning_rate: 0.1
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42
  eval_metric: "mlogloss"

rf_params:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1
  random_state: 42
  n_jobs: -1

# Model save path
model_save_path: "data/06_models"

feature_store:
  api_key: rnzJVdj1CwYpimJU.ZCavQF9nAEahE3SAgQrcZSV5yUGR8howtJHJBnEBblHvWv5I9rJ618wo61ah5qQe
  project_name: project2
  base_version: 1
  chunk_size: 50000
  max_retries: 3
  use_expectations: true

feature_groups_config:
  personal_information:
    columns:
    - age_at_injury
    - birth_year
    description: Personal demographic information of the injured worker
    features_desc:
      age_at_injury: '[Original: "Age at Injury"] Age of the worker at the time of injury'
      birth_year: '[Original: "Birth Year"] Birth year of the worker'
  financial_features:
    columns:
    - average_weekly_wage
    - number_of_dependents
    description: Financial information related to worker compensation
    features_desc:
      average_weekly_wage: '[Original: "Average Weekly Wage"] Average weekly wage of the injured worker'
      number_of_dependents: '[Original: "Number of Dependents"] Number of dependents of the worker'
  medical_case_processing:
    columns:
    - ime_4_count
    description: Medical and case processing indicators
    features_desc:
      ime_4_count: '[Original: "IME-4 Count"] Count of Independent Medical Examinations (IME-4)'
  geographic_administrative:
    columns:
    - county_of_injury
    - district_name
    - zip_code
    description: Geographic and administrative location information
    features_desc:
      county_of_injury: '[Original: "County of Injury"] County where the injury occurred'
      district_name: '[Original: "District Name"] District name for administrative purposes'
      zip_code: '[Original: "Zip Code"] ZIP code of the location'
  injury_industry_classification:
    columns:
    - wcio_nature_of_injury_code
    - industry_code
    - wcio_cause_of_injury_code
    - wcio_part_of_body_code
    description: Injury and industry classification codes
    features_desc:
      wcio_nature_of_injury_code: '[Original: "WCIO Nature of Injury Code"] Workers'' Compensation nature of injury code'
      industry_code: '[Original: "Industry Code"] Industry classification code'
      wcio_cause_of_injury_code: '[Original: "WCIO Cause of Injury Code"] Workers'' Compensation cause of injury code'
      wcio_part_of_body_code: '[Original: "WCIO Part Of Body Code"] Workers'' Compensation body part affected code'
  medical_fee_regions:
    columns:
    - medical_fee_region_ii
    - medical_fee_region_iii
    - medical_fee_region_iv
    - medical_fee_region_uk
    description: Medical fee region indicators
    features_desc:
      medical_fee_region_ii: '[Original: "Medical Fee Region_II"] Indicator for Medical Fee Region II'
      medical_fee_region_iii: '[Original: "Medical Fee Region_III"] Indicator for Medical Fee Region III'
      medical_fee_region_iv: '[Original: "Medical Fee Region_IV"] Indicator for Medical Fee Region IV'
      medical_fee_region_uk: '[Original: "Medical Fee Region_UK"] Indicator for Medical Fee Region UK'
  special_indicators:
    columns:
    - covid_19_indicator_y
    - risk_level
    - holiday_accident
    - weekend_accident
    description: Special indicators and risk assessments
    features_desc:
      covid_19_indicator_y: '[Original: "COVID-19 Indicator_Y"] Indicator if injury is related to COVID-19'
      risk_level: '[Original: "Risk_Level"] Risk level assessment for the case'
      holiday_accident: '[Original: "Holiday_Accident"] Indicator if accident occurred on a holiday'
      weekend_accident: '[Original: "Weekend_Accident"] Indicator if accident occurred on a weekend'
  seasonal_features:
    columns:
    - accident_season_sin
    - accident_season_cos
    description: Seasonal features derived from accident dates
    features_desc:
      accident_season_sin: '[Original: "Accident_Season_Sin"] Sine component of accident season'
      accident_season_cos: '[Original: "Accident_Season_Cos"] Cosine component of accident season'

# Data upload parameters
group_name: "claim_injury_features"
description: "Claim injury prediction features uploaded to feature store"
suite_name: "processed_data_suite"
feature_descriptions:
  - name: "age_at_injury"
    description: "Age of the worker at the time of injury"
  - name: "gender_m"
    description: "Binary indicator for male gender (1=Male, 0=Female/Other)"
  - name: "average_weekly_wage"
    description: "Average weekly wage of the injured worker"
  - name: "relative_wage"
    description: "Relative wage category or level"
  - name: "ime_4_count"
    description: "Count of Independent Medical Examinations (IME-4)"
  - name: "attorney_representative_y"
    description: "Indicator if worker has legal representation"
  - name: "alternative_dispute_resolution_y"
    description: "Indicator if alternative dispute resolution was used"
  - name: "days_to_first_hearing"
    description: "Number of days from injury to first hearing"
  - name: "days_to_c2"
    description: "Number of days from injury to C-2 form submission"
  - name: "days_to_c3"
    description: "Number of days from injury to C-3 form submission"
  - name: "c_2_date_year"
    description: "Year when C-2 form was submitted"
  - name: "c_2_date_day"
    description: "Day of month when C-2 form was submitted"
  - name: "c_2_date_dayofweek"
    description: "Day of week when C-2 form was submitted"
  - name: "known_c_2_date"
    description: "Indicator if C-2 date is known/available"
  - name: "c_3_date_day"
    description: "Day of month when C-3 form was submitted"
  - name: "c_3_date_month"
    description: "Month when C-3 form was submitted"
  - name: "c_3_date_year"
    description: "Year when C-3 form was submitted"
  - name: "first_hearing_date_day"
    description: "Day of month of first hearing"
  - name: "first_hearing_date_month"
    description: "Month of first hearing"
  - name: "first_hearing_date_year"
    description: "Year of first hearing"
  - name: "first_hearing_date_dayofweek"
    description: "Day of week of first hearing"
  - name: "known_first_hearing_date"
    description: "Indicator if first hearing date is known/available"
  - name: "accident_date_year"
    description: "Year when the accident occurred"
  - name: "accident_date_month"
    description: "Month when the accident occurred"
  - name: "assembly_date_year"
    description: "Year when the case was assembled"
  - name: "carrier_type_2a_sif"
    description: "Indicator for State Insurance Fund carrier type"
  - name: "carrier_type_3a_self_public"
    description: "Indicator for Self-Insured Public carrier type"
  - name: "carrier_type_4a_self_private"
    description: "Indicator for Self-Insured Private carrier type"
  - name: "county_of_injury"
    description: "County where the injury occurred"
  - name: "district_name"
    description: "District name for administrative purposes"
  - name: "wcio_nature_of_injury_code"
    description: "Workers' Compensation nature of injury code"
  - name: "industry_code"
    description: "Industry classification code"
  - name: "wcio_cause_of_injury_code"
    description: "Workers' Compensation cause of injury code"
  - name: "wcio_part_of_body_code"
    description: "Workers' Compensation body part affected code"
  - name: "covid_19_indicator_y"
    description: "Indicator if injury is related to COVID-19"
  - name: "risk_level"
    description: "Risk level assessment for the case"
