raw_datasource_name: raw_data
raw_suite_name: raw_data_suite
raw_data_asset_name: train_data
build_data_docs: true
processed_datasource_name: model_input
processed_suite_name: processed_data_suite
processed_data_asset_name: model_train_data

# Target column for prediction
target_column: "claim_injury_type"

# Data split parameters
test_size: 0.1
val_size: 0.2
random_state: 42

# Data processing parameters
numerical_features:
  - "age_at_injury"
  - "average_weekly_wage"
  - "birth_year"
  - "ime_4_count"
  - "number_of_dependents"
  - "days_to_c2"
  - "days_to_c3"
  - "days_to_first_hearing"
  - "c_2_date_day"
  - "c_2_date_month"
  - "c_2_date_year"
  - "c_2_date_dayofweek"
  - "c_3_date_month"
  - "c_3_date_day"
  - "c_3_date_year"
  - "c_3_date_dayofweek"
  - "first_hearing_date_day"
  - "first_hearing_date_month"
  - "first_hearing_date_year"
  - "first_hearing_date_dayofweek"
  - "accident_date_day"
  - "accident_date_month"
  - "accident_date_year"
  - "accident_date_dayofweek"
  - "assembly_date_day"
  - "assembly_date_month"
  - "assembly_date_year"
  - "assembly_date_dayofweek"

categorical_features:
  - "alternative_dispute_resolution_u"
  - "alternative_dispute_resolution_y"
  - "county_of_injury"
  - "district_name"
  - "industry_code"
  - "known_accident_date"
  - "known_assembly_date"
  - "known_c_2_date"
  - "known_c_3_date"
  - "wcio_cause_of_injury_code"
  - "wcio_nature_of_injury_code"
  - "wcio_part_of_body_code"
  - "zip_code"
  - "attorney_representative_y"
  - "carrier_type_2a_sif"
  - "carrier_type_3a_self_public"
  - "carrier_type_4a_self_private"
  - "carrier_type_5d_special_fund_unknown"
  - "carrier_type_unknown"
  - "covid_19_indicator_y"
  - "medical_fee_region_ii"
  - "medical_fee_region_iii"
  - "medical_fee_region_iv"
  - "medical_fee_region_uk"
  - "known_first_hearing_date"
  - "known_age_at_injury"
  - "known_birth_year"
  - "holiday_accident"
  - "weekend_accident"
  - "risk_level"
  - "gender_m"
  - "gender_unknown"
  - "accident_season_sin"
  - "accident_season_cos"
  - "relative_wage"
  - "financial_impact_category"
  - "age_group"

scaling_method: "standard"
imputation_method: "median"

# Feature engineering parameters
date_columns:
  - "c_2_date"
  - "c_3_date"
  - "first_hearing_date"
  - "accident_date"
  - "assembly_date"

create_polynomial_features: false
polynomial_degree: 2

# Feature selection parameters
xgb_threshold: "median"
rf_threshold: "median"
max_features: null
selection_method: "union"

# Model parameters
xgb_params:
  n_estimators: 100
  max_depth: 6
  learning_rate: 0.1
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42
  eval_metric: "mlogloss"

rf_params:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1
  random_state: 42
  n_jobs: -1

# Model save path
model_save_path: "data/06_models"

feature_store:
  api_key: rnzJVdj1CwYpimJU.ZCavQF9nAEahE3SAgQrcZSV5yUGR8howtJHJBnEBblHvWv5I9rJ618wo61ah5qQe
  project_name: project2
  base_version: 1
  chunk_size: 50000
  max_retries: 3
  use_expectations: true

feature_groups_config:
  personal_information:
    columns:
      - age_at_injury
      - birth_year
      - gender
    description: Personal demographic information of the injured worker
    features_desc:
      age_at_injury: '[Original: "Age at Injury"] Age of the worker at the time of injury'
      birth_year: '[Original: "Birth Year"] Birth year of the worker'
      gender: '[Original: "Gender"] Gender of the worker'
  financial_features:
    columns:
      - average_weekly_wage
      - number_of_dependents
    description: Financial information related to worker compensation
    features_desc:
      average_weekly_wage: '[Original: "Average Weekly Wage"] Average weekly wage of the injured worker'
      number_of_dependents: '[Original: "Number of Dependents"] Number of dependents of the worker'
  medical_case_processing:
    columns:
      - ime_4_count
      - attorney_representative
      - alternative_dispute_resolution
    description: Medical and case processing indicators
    features_desc:
      ime_4_count: '[Original: "IME-4 Count"] Count of Independent Medical Examinations (IME-4)'
      attorney_representative: '[Original: "Attorney/Representative"] Legal representation indicator'
      alternative_dispute_resolution: '[Original: "Alternative Dispute Resolution"] ADR usage indicator'
  geographic_administrative:
    columns:
      - county_of_injury
      - district_name
      - zip_code
    description: Geographic and administrative location information
    features_desc:
      county_of_injury: '[Original: "County of Injury"] County where the injury occurred'
      district_name: '[Original: "District Name"] District name for administrative purposes'
      zip_code: '[Original: "Zip Code"] ZIP code of the location'
  injury_industry_classification:
    columns:
      - wcio_nature_of_injury_code
      - industry_code
      - wcio_cause_of_injury_code
      - wcio_part_of_body_code
    description: Injury and industry classification codes
    features_desc:
      wcio_nature_of_injury_code: '[Original: "WCIO Nature of Injury Code"] Workers'' Compensation nature of injury code'
      industry_code: '[Original: "Industry Code"] Industry classification code'
      wcio_cause_of_injury_code: '[Original: "WCIO Cause of Injury Code"] Workers'' Compensation cause of injury code'
      wcio_part_of_body_code: '[Original: "WCIO Part Of Body Code"] Workers'' Compensation body part affected code'
  medical_fee_regions:
    columns:
      - medical_fee_region
    description: Medical fee region information
    features_desc:
      medical_fee_region: '[Original: "Medical Fee Region"] Medical fee region classification'
  special_indicators:
    columns:
      - covid_19_indicator
      - agreement_reached
      - wcb_decision
    description: Special indicators and case outcomes
    features_desc:
      covid_19_indicator: '[Original: "COVID-19 Indicator"] Indicator if injury is related to COVID-19'
      agreement_reached: '[Original: "Agreement Reached"] Indicator if agreement was reached'
      wcb_decision: '[Original: "WCB Decision"] Workers Compensation Board decision'
  temporal_features:
    columns:
      - accident_date
      - assembly_date
      - c_2_date
      - c_3_date
      - first_hearing_date
    description: Temporal features and dates
    features_desc:
      accident_date: '[Original: "Accident Date"] Date when the accident occurred'
      assembly_date: '[Original: "Assembly Date"] Date when the case was assembled'
      c_2_date: '[Original: "C-2 Date"] Date of C-2 form submission'
      c_3_date: '[Original: "C-3 Date"] Date of C-3 form submission'
      first_hearing_date: '[Original: "First Hearing Date"] Date of first hearing'

# Data upload parameters
group_name: "claim_injury_features"
description: "Claim injury prediction features uploaded to feature store"
suite_name: "processed_data_suite"
feature_descriptions:
  - name: "age_at_injury"
    description: "Age of the worker at the time of injury"
  - name: "gender_m"
    description: "Binary indicator for male gender (1=Male, 0=Female/Other)"
  - name: "average_weekly_wage"
    description: "Average weekly wage of the injured worker"
  - name: "relative_wage"
    description: "Relative wage category or level"
  - name: "ime_4_count"
    description: "Count of Independent Medical Examinations (IME-4)"
  - name: "attorney_representative_y"
    description: "Indicator if worker has legal representation"
  - name: "alternative_dispute_resolution_y"
    description: "Indicator if alternative dispute resolution was used"
  - name: "days_to_first_hearing"
    description: "Number of days from injury to first hearing"
  - name: "days_to_c2"
    description: "Number of days from injury to C-2 form submission"
  - name: "days_to_c3"
    description: "Number of days from injury to C-3 form submission"
  - name: "c_2_date_year"
    description: "Year when C-2 form was submitted"
  - name: "c_2_date_day"
    description: "Day of month when C-2 form was submitted"
  - name: "c_2_date_dayofweek"
    description: "Day of week when C-2 form was submitted"
  - name: "known_c_2_date"
    description: "Indicator if C-2 date is known/available"
  - name: "c_3_date_day"
    description: "Day of month when C-3 form was submitted"
  - name: "c_3_date_month"
    description: "Month when C-3 form was submitted"
  - name: "c_3_date_year"
    description: "Year when C-3 form was submitted"
  - name: "first_hearing_date_day"
    description: "Day of month of first hearing"
  - name: "first_hearing_date_month"
    description: "Month of first hearing"
  - name: "first_hearing_date_year"
    description: "Year of first hearing"
  - name: "first_hearing_date_dayofweek"
    description: "Day of week of first hearing"
  - name: "known_first_hearing_date"
    description: "Indicator if first hearing date is known/available"
  - name: "accident_date_year"
    description: "Year when the accident occurred"
  - name: "accident_date_month"
    description: "Month when the accident occurred"
  - name: "assembly_date_year"
    description: "Year when the case was assembled"
  - name: "carrier_type_2a_sif"
    description: "Indicator for State Insurance Fund carrier type"
  - name: "carrier_type_3a_self_public"
    description: "Indicator for Self-Insured Public carrier type"
  - name: "carrier_type_4a_self_private"
    description: "Indicator for Self-Insured Private carrier type"
  - name: "county_of_injury"
    description: "County where the injury occurred"
  - name: "district_name"
    description: "District name for administrative purposes"
  - name: "wcio_nature_of_injury_code"
    description: "Workers' Compensation nature of injury code"
  - name: "industry_code"
    description: "Industry classification code"
  - name: "wcio_cause_of_injury_code"
    description: "Workers' Compensation cause of injury code"
  - name: "wcio_part_of_body_code"
    description: "Workers' Compensation body part affected code"
  - name: "covid_19_indicator_y"
    description: "Indicator if injury is related to COVID-19"
  - name: "risk_level"
    description: "Risk level assessment for the case"
